### PR TITLE
Fix has_command, CentOS detection, source installation and add OS update support

### LINKED ISSUE #6: debian stable requires lsb_release
This is a depext outside of normal OPAM's, so might be worth trying a heuristic if it doesnt exist.  Its not installed by default in Debian Wheezy afaict.

### PR DESCRIPTION
**Pull request by avsm**
```
$ command -v fooooo
$ echo $?
1
$ /bin/sh -c command -v foooo
$ echo $?
0
```

We now just call `command` directly, which fixes #6

### CODE REVIEW

File: depext.ml [hunk 1]
```diff
@@ -41,11 +41,11 @@ let string_split char str =
   aux 0
 
 let has_command c =
-  let cmd = Printf.sprintf "/bin/sh -c command -v %s" c in
+  let cmd = Printf.sprintf "command -v %s" c in
```
Comment (dbuenzli) [inline depext.ml:44]: I'm not sure this will work well. Based on experience with cmdliner [that's](https://github.com/dbuenzli/cmdliner/blob/master/src/cmdliner.ml#L349-L355) a correct and multiplatform way of checking whether a command exists or not.

**Comment by avsm** [comment]
This pull request has become a bit feature packed :)  I'm using it in the bulk builds with all this now though...

File: depext.ml (hunk 1 above)
Comment (avsm) [inline depext.ml:44]: `command` is POSIX, but I can believe that it's not portable despite that.  Would it be possible for `cmdliner` to expose the `find_cmd` logic so that we dont have to cut and paste it here?

Comment (dbuenzli) [inline depext.ml:44]: > Would it be possible for cmdliner to expose the find_cmd logic so that we dont have to cut and paste it here?

I don't think `cmdliner` is the place to expose such things. I'd say either just c&p or use Bos which [exposes](http://erratique.ch/software/bos/doc/Bos.OS.Cmd.html#VALexists) this logic in its API (but that's another dependency).

**Comment by AltGr** [comment]
Awesome! :)
